### ISSUE TITLE
HD44780 takes ownership of `Delay`

### ISSUE THREAD

**Issue by fuchsnj** [JohnDoneth/hd44780-driver#16]
The `HD44780` struct takes exclusive ownership of `Delay`, which makes it impossible to use on devices where `Delay` can only be created once, and can't be cloned (such as a [bluepill board](https://docs.rs/stm32f1xx-hal/0.6.1/stm32f1xx_hal/delay/struct.Delay.html))

It would be nice if the `HD44780` struct didn't hold the `Delay`, and it could be passed into functions as a reference as needed.

**Comment by JohnDoneth** [comment]
Could you see if using master fixes this issue for you? #15 was merged after the last release.

**Comment by fuchsnj** [comment]
Yes, master works perfectly. Thanks!
