### ISSUE TITLE
Update crate to version 0.3.0

### ISSUE THREAD

**Issue by mycognosist** [JohnDoneth/hd44780-driver#7]
Thanks very much for your work on this package. It was a relatively effortless process to initialize and write to my Winstar WH1602B display.

I noticed that the package on crates.io is still at version 0.2.1, while the repo is now at 0.3.0. Could you please publish the latest version when you have a chance?

Thanks in advance!

**Comment by JohnDoneth** [comment]
Of course, thank you for the reminder! Sorry for the delay.

**Comment by JohnDoneth** [comment]
Done! 🎉
